<script lang="ts">
	import { ChevronLeft, Leaf, AlertTriangle } from 'lucide-svelte';

	const LAST_UPDATED = 'May 2026';
</script>

<svelte:head>
	<title>Terms and Conditions — FarmTrack</title>
	<meta name="description" content="Terms and conditions for using FarmTrack." />
</svelte:head>

<!-- Hero -->
<div class="bg-gradient-to-br from-[#1b4332] via-[#2d6a4f] to-[#40916c] text-white px-5 pt-6 pb-10 rounded-b-[2rem]">
	<a href="/" class="inline-flex items-center gap-1 text-white/70 text-sm mb-4 hover:text-white">
		<ChevronLeft size={16} />
		Home
	</a>
	<div class="flex items-center gap-2 mb-3">
		<div class="w-9 h-9 rounded-full bg-white/20 flex items-center justify-center">
			<Leaf size={18} class="text-white" />
		</div>
		<span class="font-bold text-lg tracking-tight">FarmTrack</span>
	</div>
	<h1 class="text-2xl font-bold leading-tight">Terms and Conditions</h1>
	<p class="text-white/70 text-sm mt-1">Last updated: {LAST_UPDATED}</p>
</div>

<div class="px-4 -mt-4 space-y-4 pb-24 max-w-2xl mx-auto">
	<div class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-3">
		<p class="text-sm text-base-content/80 leading-relaxed">
			Welcome to FarmTrack. These Terms and Conditions ("Terms") explain the rules for using the FarmTrack app and services ("FarmTrack", "the Service", "we", "us", "our"). By using FarmTrack, you agree to these Terms. If you do not agree, please do not use the Service.
		</p>
		<p class="text-sm text-base-content/80 leading-relaxed">
			Please read this carefully — especially the sections on the limits of our guidance and your own responsibility.
		</p>
	</div>

	<!-- Section 1 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">1. What FarmTrack is — and what it is not</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			FarmTrack provides <span class="font-semibold">general information and guidance</span> on animal health, husbandry, feeding, and disease prevention to help you make better decisions and know when to seek help.
		</p>
		<p class="text-sm text-base-content/80 leading-relaxed">
			FarmTrack is <span class="font-semibold">not</span> a veterinarian and <span class="font-semibold">does not provide veterinary, medical, or professional services</span>. Using FarmTrack does not create a vet–client–patient relationship. Our guidance is for general information only and is <span class="font-semibold">not a diagnosis, prescription, or treatment plan</span> for any specific animal.
		</p>
		<p class="text-sm text-base-content/80 leading-relaxed">
			For diagnosis, treatment, medication, and emergencies, you must consult a licensed veterinarian or qualified animal health professional. FarmTrack is a starting point, not a substitute for professional care.
		</p>
	</section>

	<!-- Section 2 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">2. Our best efforts — and the limits of our information</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			We work hard to make the information in FarmTrack accurate, current, and useful, and we apply our best efforts to that end. However:
		</p>
		<ul class="text-sm text-base-content/80 list-disc pl-5 space-y-1">
			<li>Animal health is complex, and every animal and situation is different.</li>
			<li>Information may be <span class="font-semibold">incomplete, out of date, or not suited to your exact situation</span>.</li>
			<li>Some guidance is generated by automated systems, which can make mistakes.</li>
			<li>We do <span class="font-semibold">not guarantee</span> that any information is accurate, complete, reliable, or fit for a particular purpose.</li>
		</ul>
		<p class="text-sm text-base-content/80 leading-relaxed">
			You should always use your own judgement and confirm important decisions with a qualified professional.
		</p>
	</section>

	<!-- Section 3 -->
	<section class="bg-warning/10 border border-warning/30 rounded-2xl p-5 space-y-2">
		<div class="flex items-start gap-2">
			<AlertTriangle size={18} class="text-warning shrink-0 mt-0.5" />
			<h2 class="font-bold text-base">3. Use at your own risk</h2>
		</div>
		<p class="text-sm text-base-content/80 leading-relaxed font-semibold">
			You use FarmTrack, and act on its guidance, entirely at your own risk.
		</p>
		<p class="text-sm text-base-content/80 leading-relaxed">
			You are solely responsible for any decision you make and any action you take based on information from FarmTrack — including decisions about your animals, treatments, medications, purchases, or sales. We are not responsible for outcomes that result from your use of the Service.
		</p>
		<p class="text-sm text-base-content/80 leading-relaxed">
			If you believe an animal is sick, injured, or at risk, or if there is any sign of a disease that can spread to other animals or to people, seek qualified help immediately. Do not delay professional care because of anything FarmTrack tells you.
		</p>
	</section>

	<!-- Section 4 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">4. Fair and proper use</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">We ask that you use FarmTrack fairly and responsibly. You agree to:</p>
		<ul class="text-sm text-base-content/80 list-disc pl-5 space-y-1">
			<li>Use the Service only for lawful purposes and for your own genuine farming and animal-care needs.</li>
			<li>Provide honest and accurate information when asking for guidance.</li>
			<li><span class="font-semibold">Not</span> misuse the Service — including attempting to disrupt it, copy or resell it, scrape or extract its content in bulk, reverse-engineer it, or use it to build a competing product.</li>
			<li><span class="font-semibold">Not</span> rely on FarmTrack for anything it is not designed to do, such as human medical advice, legal advice, or financial advice.</li>
		</ul>
		<p class="text-sm text-base-content/80 leading-relaxed">
			The content within FarmTrack is provided for your <span class="font-semibold">personal and farm use</span>. You may not reproduce, republish, or distribute it commercially without our written permission.
		</p>
	</section>

	<!-- Section 5 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">5. Third-party information (vets, prices, directories)</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			FarmTrack may show information drawn from third-party sources — such as directories of veterinarians and agro-vet shops, price information, and disease data. We share this to be helpful, but:
		</p>
		<ul class="text-sm text-base-content/80 list-disc pl-5 space-y-1">
			<li>We do <span class="font-semibold">not</span> control or guarantee the accuracy, availability, or quality of third-party information or services.</li>
			<li>Prices, contacts, and availability change and may be out of date.</li>
			<li>Any dealing you have with a third party (such as a vet, dealer, or seller) is between you and them. We are not a party to it and are not responsible for it.</li>
		</ul>
		<p class="text-sm text-base-content/80 leading-relaxed">Always confirm details directly before relying on them.</p>
	</section>

	<!-- Section 6 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">6. Medications and food safety</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			FarmTrack does not prescribe medication or exact dosages. Any information about drugs, doses, vaccines, or withdrawal periods is general only and must be confirmed with a vet or agro-vet professional. You are responsible for the safe and lawful use of any medication, and for observing withdrawal periods before selling or consuming meat, milk, or eggs from treated animals.
		</p>
	</section>

	<!-- Section 7 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">7. Limitation of liability</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			To the fullest extent allowed by law, FarmTrack, FastForward Livestock Venture Studio, our partners, funders, and our team will <span class="font-semibold">not be liable</span> for any loss or damage — including loss of animals, income, profits, or data, or any indirect or consequential loss — arising from your use of, or inability to use, the Service or its guidance.
		</p>
		<p class="text-sm text-base-content/80 leading-relaxed">
			Where liability cannot be excluded by law, it is limited to the maximum extent permitted.
		</p>
	</section>

	<!-- Section 8 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">8. Your account and information</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			You are responsible for keeping your account details secure and for activity under your account. We handle personal information responsibly and will publish a full privacy policy in a future update; that policy will form part of these Terms when published.
		</p>
	</section>

	<!-- Section 9 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">9. Intellectual property</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			FarmTrack, including its name, content, design, and software, is owned by FastForward Livestock Venture Studio or its licensors and is protected by law. We grant you a personal, limited, non-transferable right to use the Service under these Terms. All other rights are reserved.
		</p>
	</section>

	<!-- Section 10 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">10. Changes to the Service and these Terms</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			We may update, change, or discontinue parts of the Service at any time. We may also update these Terms from time to time. When we do, we will update the "Last updated" date above. Your continued use of FarmTrack after changes means you accept the updated Terms.
		</p>
	</section>

	<!-- Section 11 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">11. Governing law</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">
			These Terms are governed by the laws of the Federal Republic of Nigeria, and any disputes will be handled by the courts of Nigeria, unless the law requires otherwise.
		</p>
	</section>

	<!-- Section 12 -->
	<section class="bg-white rounded-2xl p-5 shadow-sm border border-base-300/50 space-y-2">
		<h2 class="font-bold text-base">12. Contact us</h2>
		<p class="text-sm text-base-content/80 leading-relaxed">If you have questions about these Terms, contact us at:</p>
		<ul class="text-sm text-base-content/80 space-y-1">
			<li><span class="font-semibold">Email:</span> <a href="mailto:hello@livestockfunds.com" class="text-primary hover:underline">hello@livestockfunds.com</a></li>
			<li><span class="font-semibold">Website:</span> <a href="https://www.livestockfunds.com" target="_blank" rel="noopener noreferrer" class="text-primary hover:underline">www.livestockfunds.com</a></li>
		</ul>
	</section>

	<p class="text-[11px] text-center text-base-content/40 pt-2 italic">
		FarmTrack is a product of FastForward Livestock Venture Studio, supported by a grant from SAIS, implemented by GIZ on behalf of the German Government.
	</p>

	<p class="text-[11px] text-center text-base-content/40">
		<a href="/about" class="hover:text-base-content/70">About FarmTrack</a>
	</p>
</div>
